/* Portable appearance wrapper; the economic envelope and schema are unchanged. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./save-format'):root.WTTNSave,typeof module==='object'&&module.exports?require('./appearance-model'):root.WTTNAppearance);if(typeof module==='object'&&module.exports)module.exports=api;root.WTTNFullBackup=api;})(globalThis,function(S,A){'use strict';
const KIND='word-to-the-nations-full-backup',RECOVERY_KEY='wttn.full-backup.recovery.v1',JOURNAL_KEY='wttn.full-backup.pending.v1';
function make(economic,placements){S.parseSaveText(economic);const checked=A.validate(placements);if(!checked.ok)throw new Error(checked.reason);const payload={kind:KIND,version:1,economic,appearance:{version:1,placements:checked.placements}};return JSON.stringify({...payload,checksum:S.hashString(JSON.stringify(payload))});}
function parse(text){if(typeof text!=='string'||text.length>S.MAX_SAVE_TEXT_CHARS)throw new Error('Backup exceeds the size limit.');const v=JSON.parse(text);if(v?.kind!==KIND)return {...S.parseSaveText(text),full:false,economic:text};if(v.version!==1||typeof v.economic!=='string'||v.appearance?.version!==1||Object.keys(v).some(k=>!['kind','version','economic','appearance','checksum'].includes(k))||Object.keys(v.appearance).some(k=>!['version','placements'].includes(k)))throw new Error('Unsupported full backup format.');const payload={kind:KIND,version:1,economic:v.economic,appearance:v.appearance};if(S.hashString(JSON.stringify(payload))!==v.checksum)throw new Error('Full backup checksum mismatch.');const checked=A.restore(v.appearance.placements);if(!checked.ok)throw new Error(checked.reason);const parsed=S.parseSaveText(v.economic);return {...parsed,full:true,economic:v.economic,placements:checked.placements};}
function recoverPending(storage,keys){const raw=storage.getItem(JOURNAL_KEY);if(!raw)return null;const prior=parse(raw);if(!prior.full)throw new Error('Invalid import recovery journal.');let prefs={};try{prefs=JSON.parse(storage.getItem(keys.preferences)||'{}');}catch(_){}prefs.placements=prior.placements;prefs.decorations=Object.keys(prior.placements);storage.setItem(keys.save,prior.economic);storage.setItem(keys.preferences,JSON.stringify(prefs));storage.removeItem(JOURNAL_KEY);return prior.placements;}
function commit(storage,parsed,currentEnvelope,currentPreferences,keys){if(!parsed.full)throw new Error('Full backup required.');const validated=parse(make(parsed.economic,parsed.placements)),recovery=make(currentEnvelope,currentPreferences.placements||{}),newPrefs={...currentPreferences,placements:validated.placements,decorations:Object.keys(validated.placements)};
 // A valid recovery journal is durable before either primary value changes.
 try{storage.setItem(RECOVERY_KEY,recovery);storage.setItem(JOURNAL_KEY,recovery);storage.setItem(keys.backup,currentEnvelope);storage.setItem(keys.save,S.makeEnvelope(validated.state));storage.setItem(keys.preferences,JSON.stringify(newPrefs));storage.removeItem(JOURNAL_KEY);}catch(error){try{recoverPending(storage,keys);}catch(_){/* Next startup retries the intact journal. */}throw new Error('Full backup could not be stored. Current progress was not imported. '+error.message);}return newPrefs;}
return {KIND,RECOVERY_KEY,JOURNAL_KEY,make,parse,commit,recoverPending};
});
