const {chromium}=require(process.env.WTTN_PLAYWRIGHT || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const G=require('../game-core.js'),S=require('../save-format.js');
process.chdir(path.resolve(__dirname,'..'));
const out=path.resolve(process.env.WTTN_QA_OUTPUT || 'docs/qa/screenshots');fs.mkdirSync(out,{recursive:true});
const result={browser:'Microsoft Edge headless (desktop emulation)',checks:[],errors:[],layouts:[]};
function fixture(advanced=false){const s=G.createState();s.pages=G.bn('1e18');s.peakPages=G.bn('1e18');s.translations=12;s.ti=G.bn(1000);s.lifetimeTi=G.bn(1200);s.networks=6;s.lifetimeNc=G.bn(30);s.nc=G.bn(12);s.phase2Complete=true;s.phase3Complete=true;s.ncThisField=G.bn(1);Object.keys(s.tiOneTime).forEach(k=>s.tiOneTime[k]=true);Object.keys(s.producers).forEach(k=>s.producers[k]=25);s.system.offlineEnabled=false;Object.keys(s.automation.controls).forEach(k=>s.automation.controls[k]=false);if(advanced){s.fe=G.bn(100);s.lifetimeFe=G.bn(100);s.feThisLegacy=G.bn(100);s.legacies=2;s.legacy=G.bn(12);s.lifetimeLegacy=G.bn(12);s.phase4Complete=true;s.field.cleared=['urban','remote','oral','restricted','multilingual'];s.field.index=5;G.SCRIPTURE_COLLECTIONS.forEach(x=>s.library[x.id]=true)}return S.makeEnvelope(s)}
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge',args:['--disable-features=PaintHolding']});
async function page(save){const c=await b.newContext({viewport:{width:1366,height:768},reducedMotion:'reduce',serviceWorkers:'block'});if(save)await c.addInitScript(s=>{if(!sessionStorage.getItem('fixture')){localStorage.setItem('wttn.phase6.save.v6',s);sessionStorage.setItem('fixture','yes')}},save);const p=await c.newPage();p.on('pageerror',e=>result.errors.push(e.message));await p.goto('http://127.0.0.1:8080/dist/web/');await p.waitForTimeout(200);await p.waitForFunction(()=>window.WTTN_READY);return p}
async function shot(p,name){await p.waitForTimeout(150);const c=await p.context().newCDPSession(p);const s=await c.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(s.data,'base64'));await c.detach()}
let p=await page();
for(const [w,h] of [[320,568],[390,844],[430,932],[768,1024],[1024,768],[1366,768],[1920,1080],[844,390]]){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(50);const r=await p.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,buy:document.querySelector('#workDecisionCockpit button')?.getBoundingClientRect().toJSON()}));result.layouts.push({w,h,...r});assert(!r.overflow,`overflow ${w}`);await shot(p,`fresh-${w}x${h}`)}
await p.setViewportSize({width:1366,height:768});await p.locator('[data-producer="scribe"]').waitFor();await p.waitForFunction(()=>document.querySelector('[data-producer="scribe"]').getAttribute('aria-disabled') === 'false');await p.locator('[data-producer="scribe"]').click();await p.waitForTimeout(600);assert.match(await p.locator('#producer-scribe .count').innerText(),/1/);assert.equal(await p.evaluate(()=>document.activeElement.dataset.producer),'scribe');result.checks.push('Fresh purchase changes ownership and retains focus through ticks');
await p.locator('#producer-scribe summary').click();await p.waitForTimeout(600);assert(await p.locator('#producer-scribe details').getAttribute('open')!==null);result.checks.push('Open producer reading persists through updates');
await p.locator('[data-buy-amount="10"]').click();assert.match(await p.locator('[data-producer="scribe"]').innerText(),/10/);result.checks.push('Quantity selection');
await p.locator('#mobileMenuButton').click();await p.locator('#exportBtn').click();assert(await p.locator('#exportText').inputValue());await p.locator('#exportDialog .dialog-close').click();
await p.locator('#mobileMenuButton').click();await p.locator('#importBtn').click();await p.locator('#importText').fill('not a save');await p.locator('#importTextBtn').click();assert(await p.locator('#importFeedback').innerText());await p.locator('#importDialog .dialog-close').click();result.checks.push('Export text and invalid import feedback');
await p.locator('[data-tab="system"]').click();await p.locator('#resetBtn').click();await p.locator('#cancelConfirmBtn').click();assert.match(await p.locator('#pagesValue').innerText(),/\d/);await p.locator('#textScale').selectOption('120');result.checks.push('Reset cancellation and 120% text preference');await shot(p,'system-text-120');await p.reload();await p.waitForFunction(()=>window.WTTN_READY);result.checks.push('Reload after saved preferences');
await p.context().close();p=await page(fixture());await p.locator('[data-tab="projects"]').click();await shot(p,'projects');await p.locator('#atlasOverviewBtn').click();await p.locator('#atlasZoomInBtn').click();await p.locator('#atlasResetViewBtn').click();await p.locator('#atlasFieldPicker').selectOption('urban');await p.locator('#openAtlasSelectedFieldBtn').click();assert(await p.locator('#atlasDossier').isVisible());await shot(p,'developed-atlas');await p.locator('#atlasDossierGo').click();assert(await p.locator('#tab-fields').isVisible());result.checks.push('Developed Atlas zoom, Fit, selector, adjacent dossier and field navigation');
await p.context().close();p=await page(fixture(true));for(const tab of ['work','projects','translation','insight','network','fields','legacy','scripture','stats','system']){await p.locator(`[data-tab="${tab}"]`).click();assert(await p.locator(`#tab-${tab}`).isVisible());await shot(p,`advanced-${tab}`)}result.checks.push('Every major screen accessible with advanced fixture');
await p.locator('[data-tab="scripture"]').click();await p.locator('.library-deep-dive summary').first().click();await p.waitForTimeout(600);assert(await p.locator('.library-deep-dive').first().getAttribute('open')!==null);await shot(p,'scripture-reading');result.checks.push('Scripture reading stays open');
await p.setViewportSize({width:390,height:844});await p.locator('#chamberMore').click();await p.locator('[data-tab="legacy"]').click();assert(await p.locator('#tab-legacy').isVisible());await shot(p,'phone-legacy');result.checks.push('Phone More navigation exposes advanced screens');
await p.setViewportSize({width:1366,height:768});await p.emulateMedia({forcedColors:'active'});await shot(p,'forced-colors');result.checks.push('Forced-colors rendering inspected');await p.context().close();
const c=await b.newContext({serviceWorkers:'block'});p=await c.newPage();await p.goto('file:///'+path.resolve('dist/Word-to-the-Nations.html').replace(/\\/g,'/'));await p.waitForFunction(()=>window.WTTN_READY);await c.setOffline(true);await p.reload();await p.waitForFunction(()=>window.WTTN_READY);result.checks.push('Actual portable file opens and reloads offline');await c.close();await b.close();fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})().catch(e=>{result.errors.push(e.stack);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));console.error(e);process.exit(1)});
