'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const Sync=require('../cloud-sync'),Snapshot=require('../cloud-snapshot'),G=require('../game-core'),S=require('../save-format'),F=require('../full-backup');
class Storage { constructor(){this.map=new Map();this.drop=false;} getItem(k){return this.map.get(k)??null;} setItem(k,v){if(!this.drop)this.map.set(k,String(v));} removeItem(k){this.map.delete(k);} }
const snapshot=(n=0,t=1000)=>{const s=G.createState();s.pages=G.bn(100+n);s.producers.scribe=n;return F.make(S.makeEnvelope(s,t),{});};
function server(){let row={revision:0,snapshot:null,deleted:false},writes=0,drop=false;return { get writes(){return writes;},get row(){return {...row};},loseResponse(){drop=true;}, async read(){return {...row};}, async write(p){writes++;if(row.requestId===p.requestId)return {...row,status:row.deleted?'deleted':'saved'};if(row.revision!==p.revision)return {...row,status:'conflict'};if(row.deleted&&!p.restore)return {...row,status:'deleted'};row={revision:row.revision+1,snapshot:p.snapshot,deleted:false,requestId:p.requestId};if(drop){drop=false;throw new TypeError('network response lost');}return {...row,status:'saved'};},async remove(p){if(row.revision!==p.revision)return {...row,status:'conflict'};row={revision:row.revision+1,snapshot:null,deleted:true,requestId:p.requestId};return {...row,status:'deleted'};}};}
let ids=0;function device(n=1,storage=new Storage()){let live=snapshot(n),clock=100000;const d=Sync.create({storage,initial:live,capture:()=>live,apply:s=>{F.parse(s);live=s;},validate:F.parse,meaningful:Snapshot.meaningful,fresh:()=>snapshot(0),now:()=>clock,uuid:()=>String(++ids)});return {d,storage,set:n=>live=snapshot(n),get:()=>live,advance:()=>clock+=61000};}
const tests=[];function test(name,fn){tests.push([name,fn]);}
test('guest save preserved before optional account attachment',async()=>{const a=device(),r=server();await a.d.attach({id:'A'},r);assert.equal(a.d.model().state,'offer');assert.equal(r.writes,0);assert(a.storage.getItem(Sync.PREFIX+'original'));await a.d.choose('local');assert.equal(r.row.revision,1);assert.equal(a.d.model().state,'ready');});
test('first cloud restore on untouched device, conflict on meaningful device',async()=>{const r=server(),a=device(3);await a.d.attach({id:'A'},r);await a.d.choose('local');const b=device(0);await b.d.attach({id:'A'},r);assert.equal(b.get(),r.row.snapshot);assert.equal(b.d.model().state,'ready');const c=device(2);await c.d.attach({id:'A'},r);assert.equal(c.d.model().state,'conflict');assert.equal(F.parse(c.get()).state.producers.scribe,2);});
test('stale devices never overwrite newer revisions, both choices preserve recovery',async()=>{const r=server(),a=device(),b=device(0);await a.d.attach({id:'A'},r);await a.d.choose('local');await b.d.attach({id:'A'},r);a.set(5);await a.d.sync({force:true});b.set(9);await b.d.sync({force:true});assert.equal(b.d.model().state,'conflict');assert.equal(F.parse(r.row.snapshot).state.producers.scribe,5);await b.d.choose('local');assert.equal(F.parse(r.row.snapshot).state.producers.scribe,9);assert.equal(F.parse(b.d.cloudRecovery()).state.producers.scribe,5);a.set(6);await a.d.sync({force:true});await a.d.choose('cloud');assert.equal(F.parse(a.d.recovery()).state.producers.scribe,6);assert.equal(F.parse(a.get()).state.producers.scribe,9);});
test('lost response retries exact operation without double revision',async()=>{const r=server(),a=device();await a.d.attach({id:'A'},r);r.loseResponse();await a.d.choose('local');assert.equal(a.d.model().state,'unavailable');assert.equal(r.row.revision,1);await a.d.sync({force:true});assert.equal(r.row.revision,1);assert.equal(a.d.model().state,'ready');});
test('account switching and logout keep distinct guest/account slots',async()=>{const r=server(),a=device(2);await a.d.attach({id:'A'},r);await a.d.choose('local');a.set(9);a.d.localChanged();await a.d.attach({id:'B'},server());assert.equal(F.parse(a.get()).state.producers.scribe,0);await a.d.attach(null,null);assert.equal(F.parse(a.get()).state.producers.scribe,2);await a.d.attach({id:'A'},r);assert.equal(F.parse(a.get()).state.producers.scribe,9);});
test('deletion blocks stale upload and requires explicit reenable',async()=>{const r=server(),a=device(),b=device(0);await a.d.attach({id:'A'},r);await a.d.choose('local');await b.d.attach({id:'A'},r);await a.d.remove();assert(r.row.deleted);b.set(10);await b.d.sync({force:true});assert.equal(b.d.model().state,'deleted');assert(!b.d.model().enabled);await b.d.sync({force:true});assert(r.row.deleted);await b.d.choose('local');assert(!r.row.deleted);});
test('ordinary uploads are limited to once a minute',async()=>{const r=server(),a=device();await a.d.attach({id:'A'},r);await a.d.choose('local');a.set(2);await a.d.sync();assert.equal(r.writes,1);a.advance();await a.d.sync();assert.equal(r.writes,2);});
test('silent storage failure blocks linking without discarding original',()=>{const storage=new Storage();storage.drop=true;assert.throws(()=>device(1,storage),/recovery storage/);});
test('interrupted account switch fails closed and recovers the previous owner',async()=>{const storage=new Storage();let live=snapshot(3);const d=Sync.create({storage,initial:live,capture:()=>live,apply:()=>{throw new Error('quota');},validate:F.parse,meaningful:Snapshot.meaningful,fresh:()=>snapshot(0)});await d.attach({id:'A'},server());assert.equal(d.canSave(),false);assert(storage.getItem(Sync.SWITCH));Sync.recoverSwitch(storage,s=>{live=s;});assert.equal(storage.getItem(Sync.SWITCH),null);assert.equal(storage.getItem(Sync.OWNER),'');assert.equal(F.parse(live).state.producers.scribe,3);});
test('corrupt cloud data never replaces local state',async()=>{const a=device(3);await a.d.attach({id:'A'},{read:async()=>({revision:1,snapshot:'corrupt'})});assert.equal(a.d.model().state,'unavailable');assert.equal(F.parse(a.get()).state.producers.scribe,3);});
test('account changes in another tab disable stale local writer',async()=>{const a=device();await a.d.attach({id:'A'},server());a.storage.setItem(Sync.OWNER,'B');assert.equal(a.d.canSave(),false);a.d.localChanged();assert.equal(a.d.model().state,'local-error');});
test('an old edition cannot replace the owned startup snapshot through the legacy key',async()=>{const a=device(7);await a.d.attach({id:'A'},server());a.storage.setItem('wttn.phase6.save.v6',S.makeEnvelope(G.createState()));assert.equal(F.parse(Sync.ownedSnapshot(a.storage)).state.producers.scribe,7);});
test('network failure does not turn an attached account into a guest',async()=>{const a=device();await a.d.attach({id:'A'},server());a.d.unavailable('network');assert.equal(a.d.model().user.id,'A');assert.equal(a.d.model().state,'unavailable');});
test('an in-flight upload cannot apply its response after account switching',async()=>{const a=device(),r=server();await a.d.attach({id:'A'},r);await a.d.choose('local');let release;r.write=()=>new Promise(resolve=>release=resolve);a.set(4);const pending=a.d.sync({force:true});await a.d.attach({id:'B'},server());release({status:'saved',revision:99,snapshot:snapshot(4)});await pending;assert.equal(a.d.model().user.id,'B');assert.equal(a.d.model().state,'offer');assert.equal(F.parse(a.get()).state.producers.scribe,0);});
test('response from old account is ignored after switching accounts',async()=>{const a=device();let resolve;const pending=a.d.attach({id:'A'},{read:()=>new Promise(r=>resolve=r)});await a.d.attach({id:'B'},server());resolve({revision:3,snapshot:snapshot(20)});await pending;assert.equal(a.d.model().user.id,'B');assert.equal(F.parse(a.get()).state.producers.scribe,0);});
test('unsupported newer economic state is rejected before replacement',()=>{const raw=JSON.parse(S.makeEnvelope(G.createState()));raw.state.version=999;raw.checksum=S.hashString(JSON.stringify(raw.state));assert.throws(()=>F.make(JSON.stringify(raw),{}),/newer/);});
test('cloud restores apply 1h, 8h, 1d and 7d earnings and queues once',()=>{for(const seconds of [3600,28800,86400,604800]){const state=G.createState();state.pages=G.bn(1e6);G.buyProducer(state,'scribe',5);G.buyPageUpgrade(state,'desk');G.enqueuePurchase(state,{type:'producer',id:'copyist',target:10});const before=F.make(S.makeEnvelope(state,1000),{}),expected=F.parse(before).state;G.simulateOffline(expected,seconds);const restored=Snapshot.prepare(before,1000+seconds*1000);assert.equal(JSON.stringify(restored.parsed.state.pages),JSON.stringify(expected.pages));assert.deepEqual(restored.parsed.state.producers,expected.producers);const again=Snapshot.prepare(restored.snapshot,1000+seconds*1000);assert.equal(again.summary,null);assert.equal(JSON.stringify(again.parsed.state.pages),JSON.stringify(expected.pages));}});
test('SDK and manifest use canonical authority; no credential duplication',()=>{const a=fs.readFileSync('account-adapter.js','utf8'),manifest=JSON.parse(fs.readFileSync('.well-known/thiepn-app.json'));assert(a.includes("import('/account-platform/sdk/v1/index.js')"));assert(!a.includes('setSession'));assert.equal(manifest.sessionAuthority,'thiepn-account');assert.equal(manifest.health.networkFailureLogsOutUser,false);});
(async()=>{for(const [name,run] of tests){await run();console.log('PASS '+name);}console.log(`${tests.length} cloud-save tests passed`);})().catch(e=>{console.error(e);process.exitCode=1;});
