'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=n=>fs.readFileSync(path.join(root,n),'utf8'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const web=read('dist/web/index.html'),manifest=JSON.parse(read('dist/build-manifest.json')),sourceSW=read('dist/web/sw.js');let passed=0;
async function check(name,fn){await fn();passed++;console.log('PASS '+name);}
function worker(scope='https://example.test/wttn/',{offline=false,failInstall=false}={}){
 const events={},calls={deleted:[],cached:[],fetched:[],claimed:0,skipped:0},prefix='wttn-app-'+encodeURIComponent(new URL(scope).pathname)+'-',core=prefix+manifest.buildId;
 const cache={put:async req=>calls.cached.push(req.url),keys:async()=>[],addAll:async paths=>{if(failInstall)throw Error('interrupted install');calls.cached.push(...paths);},match:async req=>{if(req===new URL('./index.html',scope).href)return {html:web};return null;}};
 const context={URL,Set,self:{registration:{scope},location:new URL(scope),clients:{claim:async()=>calls.claimed++},skipWaiting:()=>calls.skipped++,addEventListener:(n,h)=>events[n]=h},caches:{open:async name=>{assert([core,core+'-art'].includes(name));return cache;},keys:async()=>[core,core+'-art',prefix+'old','another-game','wttn-app-%2Fother%2F-old'],delete:async n=>calls.deleted.push(n)},fetch:async request=>{calls.fetched.push(request.url);if(offline)throw Error('offline');return{ok:true,fromNetwork:true,clone(){return this;}};}};
 vm.runInNewContext(sourceSW,context);return{events,calls,prefix};
}
(async()=>{
 await check('web release uses separate content-hashed scripts and CSS',()=>{assert(/<script src="[^\"]+\.[a-f0-9]{12}\.js"/.test(web));assert(/<link rel="stylesheet" href="[^\"]+\.[a-f0-9]{12}\.css"/.test(web));assert(!web.includes('data:image/webp;base64,'));assert(!fs.existsSync(path.join(root,'dist/Word-to-the-Nations.html')));});
 await check('all built JavaScript parses',()=>{for(const file of Object.values(manifest.assets).filter(n=>n.endsWith('.js')))new vm.Script(read('dist/web/'+file),{filename:file});new vm.Script(sourceSW);});
 await check('build manifest verifies every delivered file',()=>{assert.equal(manifest.version,JSON.parse(read('package.json')).version);for(const [file,digest] of Object.entries(manifest.files))assert.equal(sha(fs.readFileSync(path.join(root,'dist/web',file))),digest,file);});
 await check('all external shell resources exist at relative paths',()=>{for(const m of web.matchAll(/(?:src|href)="([^\"]+)"/g)){const n=m[1];if(n.startsWith('#')||/^(https?:|data:)/.test(n))continue;assert(!n.startsWith('/'));assert(fs.existsSync(path.join(root,'dist/web',n)),n);}});
 await check('all CSS image/font URLs resolve to hashed files',()=>{for(const file of Object.values(manifest.assets).filter(n=>n.endsWith('.css')))for(const m of read('dist/web/'+file).matchAll(/url\(['"]?([^'"\)]+)['"]?\)/g)){assert(fs.existsSync(path.join(root,'dist/web',m[1])),m[1]);}});
 await check('root and repository subdirectory manifests resolve correctly',()=>{const pwa=JSON.parse(read('dist/web/manifest.webmanifest'));for(const base of ['https://example.test/','https://example.test/games/wttn/']){assert.equal(new URL(pwa.start_url,base).href,base);assert.equal(new URL(pwa.scope,base).href,base);for(const i of pwa.icons)assert(fs.existsSync(path.join(root,'dist/web',i.src)));}});
 await check('atomic installation includes code, fonts and low-resolution visuals',async()=>{const w=worker();let pending;w.events.install({waitUntil:p=>pending=p});await pending;assert(w.calls.cached.includes('./index.html'));assert(w.calls.cached.some(x=>x.includes('terrain-low.')));assert(w.calls.cached.some(x=>x.endsWith('.woff2')));for(const x of w.calls.cached)if(x!=='./')assert(fs.existsSync(path.join(root,'dist/web',x)));});
 await check('an interrupted essential download rejects installation without forced activation',async()=>{const w=worker(undefined,{failInstall:true});let pending;w.events.install({waitUntil:p=>pending=p});await assert.rejects(pending,/interrupted/);assert.equal(w.calls.skipped,0);});
 await check('activation preserves other applications and scope caches',async()=>{const w=worker();let pending;w.events.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(w.calls.deleted,[w.prefix+'old']);assert.equal(w.calls.claimed,1);});
 await check('offline navigation reads the installed shell at root and subdirectory',async()=>{for(const scope of ['https://example.test/','https://example.test/wttn/']){const w=worker(scope,{offline:true});let result;w.events.fetch({request:{url:scope,method:'GET',mode:'navigate'},respondWith:p=>result=p});assert.equal((await result).html,web);assert.equal(w.calls.fetched.length,0);}});
 await check('cross-origin, other-app, POST and unlisted private files are not intercepted',()=>{const w=worker();for(const request of [{url:'https://other.test/wttn/',method:'GET',mode:'navigate'},{url:'https://example.test/other/',method:'GET',mode:'navigate'},{url:'https://example.test/wttn/',method:'POST',mode:'cors'},{url:'https://example.test/wttn/save.json',method:'GET',mode:'cors'}])w.events.fetch({request,respondWith:()=>assert.fail('Unexpected interception')});});
 await check('updates activate only after the explicit saved-reload command',()=>{const w=worker();w.events.message({data:{type:'OTHER'}});assert.equal(w.calls.skipped,0);w.events.message({data:{type:'SKIP_WAITING'}});assert.equal(w.calls.skipped,1);const app=read('app.js');assert(app.indexOf('if (!save(true))')<app.indexOf('swRegistration.waiting.postMessage'));});
 await check('optional artwork is cached independently; its failure leaves navigation available',async()=>{const src=manifest.assets['assets/world/terrain-high.webp'],w=worker();let response;w.events.fetch({request:{url:'https://example.test/wttn/'+src,method:'GET',mode:'cors'},respondWith:p=>response=p});assert((await response).fromNetwork);assert(w.calls.cached.some(x=>x.endsWith('.webp')));const failed=worker(undefined,{offline:true});failed.events.fetch({request:{url:'https://example.test/wttn/'+src,method:'GET',mode:'cors'},respondWith:p=>response=p});await assert.rejects(response,/offline/);failed.events.fetch({request:{url:'https://example.test/wttn/',method:'GET',mode:'navigate'},respondWith:p=>response=p});assert.equal((await response).html,web);});
 await check('byte budgets meet the accepted web thresholds',()=>{assert(manifest.initialPlayableBytes<=5e6);assert(manifest.artworkBytes<=60e6);const c={window:{}};vm.runInNewContext(read('settlement-assets.js'),c);vm.runInNewContext(read('crafted-assets.js'),c);const art=c.window.WTTNSettlementArt.assets,all=new Set();function current(phone){const requests=new Set();const add=(key,level)=>{const a=art[key];if(!a)return;requests.add(a.variants?.[level]||a.variants?.low||a.src);};for(const key of art.terrain.layerKeys)add(key,phone?'medium':'high');for(const id of ['scribe','copyist','editor','teacher','workshop','scriptorium'])add('building-'+id+'-3',phone?'medium':'high');for(const key of ['props','environment','worker-variants','work-props','environment-activity','milestones','campaign-keepsakes'])add(key,phone?'low':'medium');for(const key of ['decorations','equipment','commissions'])add(key,phone?'medium':'high');return manifest.initialPlayableBytes+[...requests].filter(s=>!s.includes('-low.')).reduce((n,s)=>n+fs.statSync(path.join(root,s)).size,0);}const desktop=current(false),phone=current(true);console.log({desktop,phone});assert(desktop<=12e6);assert(phone<=6e6);const report={initialPlayableBytes:manifest.initialPlayableBytes,currentSceneDesktopBytes:desktop,currentScenePhoneBytes:phone,completeArtworkBytes:manifest.artworkBytes,method:'Conservative initial essential-cache bytes plus all current developed-scene upgrades, including offscreen authored sites.'};fs.mkdirSync('docs/qa-v2.10',{recursive:true});fs.writeFileSync('docs/qa-v2.10/budgets.json',JSON.stringify(report,null,2));});
 await check('all Method illustrations are distinct and all nine Journey scenes exist',()=>{const c={window:{}};vm.runInNewContext(read('settlement-assets.js'),c);vm.runInNewContext(read('crafted-assets.js'),c);const hashes=Object.values(c.window.WTTNEquipmentImages).map(p=>sha(fs.readFileSync(path.join(root,p))));assert.equal(new Set(hashes).size,8);for(const id of ['urban','remote','oral','restricted','multilingual','frontier','translation','network','legacy']){const spec=c.window.WTTNSettlementArt.assets[id];assert(spec.sourceWidth>=1536);for(const src of Object.values(spec.variants))assert(manifest.assets[src]);}});
 fs.writeFileSync(path.join(root,'docs/qa-v2.10/delivery-results.json'),JSON.stringify({passed,failed:0,serviceWorkerCoverage:'Executable mocks; live browser results are reported separately'},null,2));console.log(`Delivery ${passed} passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
