'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const G=require('../game-core'),V=require('../settlement-model'),R=require('../settlement-animation'),L=require('../asset-loader');
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name);}
(async()=>{
await test('frozen economic source hashes match v2.7.0',()=>{for(const file of ['game-core.js','bignum.js','save-format.js'])assert.deepEqual(fs.readFileSync(file),fs.readFileSync(path.join('tests/baseline-v2.7',file)));});
await test('identical purchasing, planning, offline and reset command traces match the baseline',()=>{
 const baseline=require('./baseline-v2.7/game-core');const realNow=Date.now;Date.now=()=>1790190000000;
 function trace(core){const s=core.createState(),snap=[];function record(){snap.push(JSON.stringify(s));}
 for(let i=0;i<240;i++){core.tick(s,30);for(const p of core.PRODUCERS)core.buyProducer(s,p.id,i%3===0?'max':1);for(const u of core.PAGE_UPGRADES)core.buyPageUpgrade(s,u.id);if(i===10){core.setSpecialization(s,'publisher');core.enqueuePurchase(s,{type:'producer',id:'copyist',target:50});}for(const p of core.PROJECTS)core.completeProject(s,p.id);if(i%40===0)core.completeTranslation(s);if(i%80===0)core.completeNetwork(s);record();}
 for(const seconds of [3600,28800,86400,604800]){core.simulateOffline(s,seconds);record();}return snap;}
 try{assert.deepEqual(trace(G),trace(baseline));}finally{Date.now=realNow;}
});
await test('four architectural stages derive from saved milestones; inactivity is truthful',()=>{for(const [n,stage] of [[0,0],[1,1],[9,1],[10,2],[24,2],[25,3],[500,3]]){const s=G.createState();s.settlement.buildings.scribe=n;const a=V.derive(s).sites[0];assert.equal(a.stage,stage);assert.equal(a.workers,0);assert.equal(a.equipment,false);assert.equal(a.ornaments,n===500?4:0);}});
await test('return recap includes expansion and milestones without changing the economy',()=>{const s=G.createState(),before=V.derive(s);s.producers.copyist=10;const state=JSON.stringify(s),next=V.derive(s);assert.deepEqual(V.recapMilestones(before,next),['Copying Hall · 1, 10']);assert.equal(JSON.stringify(s),state);assert.deepEqual(V.recapMilestones(next,next),[]);});
await test('authored routes avoid all six building footprints',()=>{for(const route of Object.values(R.paths))for(let i=0;i<=100;i++){const p=R.sample(route,i/100);for(const b of V.sites){assert(!(p.x>b.x-b.w*.26&&p.x<b.x+b.w*.26&&p.y>b.y-b.h*.39&&p.y<b.y-9),`route crosses ${b.id} at ${JSON.stringify(p)}`);}}});
await test('activity caps and reduced-motion poses are deterministic',()=>{assert.equal(R.cap(),24);assert.equal(R.cap({phone:true}),12);assert.equal(R.cap({low:true}),6);assert.deepEqual(R.allocate(Array.from({length:6},()=>({workers:4})),6),[1,1,1,1,1,1]);assert.deepEqual(R.allocate(Array.from({length:6},()=>({workers:4})),12),[2,2,2,2,2,2]);const s={...V.sites[0],workers:4};for(let i=0;i<4;i++){const a=R.worker(s,i,100,true);assert(Number.isFinite(a.x)&&Number.isFinite(a.y));assert.deepEqual(a,R.worker(s,i,99999,true));}});
await test('failed optional assets are requested once, leaving the fallback usable',async()=>{let requests=[];function imageFactory(){let img={naturalWidth:100,naturalHeight:100};Object.defineProperty(img,'src',{set(url){requests.push(url);queueMicrotask(()=>url==='bad'?img.onerror():img.onload());}});return img;}
 const loader=L.create({art:{variants:{low:'fallback',high:'bad'}}},{imageFactory});await loader.load('art','low');const fallback=loader.get('art');await loader.load('art','high');await loader.load('art','high');assert.equal(requests.filter(x=>x==='bad').length,1);assert.equal(loader.get('art'),fallback);});
await test('image request concurrency and decoded residency are bounded',async()=>{let live=0,peak=0;function imageFactory(){const img={naturalWidth:200,naturalHeight:200};Object.defineProperty(img,'src',{set(){live++;peak=Math.max(peak,live);setImmediate(()=>{live--;img.onload();});}});return img;}
 const manifest=Object.fromEntries(Array.from({length:20},(_,i)=>['a'+i,{src:'image'+i}])),loader=L.create(manifest,{concurrency:3,maxBytes:500000,imageFactory});await Promise.all(Object.keys(manifest).map(k=>loader.load(k)));assert(peak<=3);assert(loader.stats().decodedBytes<=500000);});
await test('responsive image budgets can grow and evicted art can be reloaded',async()=>{function imageFactory(){const i={naturalWidth:200,naturalHeight:200};Object.defineProperty(i,'src',{set(){queueMicrotask(()=>i.onload());}});return i;}const loader=L.create({a:{src:'a'},b:{src:'b'}},{maxBytes:170000,imageFactory});await loader.load('a');await loader.load('b');assert(!loader.get('a'));loader.setBudget(400000);await loader.load('a');assert(loader.get('a')&&loader.get('b'));assert.equal(loader.level('a'),'low');});
await test('pinch zoom preserves the touched world point and respects zoom bounds',()=>{const camera={width:390,height:844,zoom:1,scale:1.2,panX:30,panY:-20},start={x:145,y:340,distance:100},current={x:155,y:360,distance:150},r=R.pinchCamera(camera,start,current);function point(c,p){return[(p.x-(390-1536*c.scale)/2-c.panX)/c.scale,(p.y-(844-1024*c.scale)/2-c.panY)/c.scale];}const before=point(camera,start),after=point(r,current);assert(Math.abs(before[0]-after[0])<1e-9);assert(Math.abs(before[1]-after[1])<1e-9);assert.equal(r.zoom,1.5);assert.equal(R.pinchCamera(camera,start,{...current,distance:10000}).zoom,2.4);});
await test('schema, storage, truthful portraits and safe update contracts remain intact',()=>{const core=fs.readFileSync('game-core.js','utf8'),app=fs.readFileSync('app.js','utf8'),scene=fs.readFileSync('settlement-scene.js','utf8');assert(core.includes('const VERSION = 8'));assert(app.includes("wttn.phase6.save.v6"));assert(app.indexOf('if (!save(true))')<app.indexOf("swRegistration.waiting.postMessage"));assert(!scene.includes('site.stage||1'));assert(!scene.includes('Math.min(4,model.sites.indexOf'));});
fs.mkdirSync('docs/qa-v2.9',{recursive:true});fs.writeFileSync('docs/qa-v2.9/presentation-results.json',JSON.stringify({checks,passed:checks,failed:0},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
