'use strict';
const assert=require('assert/strict'),fs=require('fs'),G=require('../game-core'),S=require('../save-format'),V=require('../settlement-model'),W=require('../workshop-model');
let checks=0;function test(name,fn){fn();checks++;console.log('PASS · '+name);}
function clone(s){return G.reviveState(JSON.parse(JSON.stringify(s)));}
test('schema 6/7 early/middle/late migration is idempotent and preserves economic progress',()=>{
 for(const version of [6,7])for(const late of [0,3,12])for(const paid of [false,true]){
  const raw=G.createState();raw.version=version;raw.pages=G.bn('1e'+(late+2));raw.peakPages=raw.pages;raw.ti=G.bn(57);raw.lifetimeTi=G.bn(800);raw.tiThisNetwork=G.bn(300);raw.translations=late;raw.networks=late?2:0;raw.legacies=late===12?2:0;raw.producers.scribe=late+1;raw.tiOneTime.buyMax=paid;raw.specialization=late?'teacher':null;
  raw.purchaseQueue={paused:true,orders:[{type:'producer',id:'copyist',target:25},{type:'method',id:'desk'}]};raw.reading={bookmarks:['john-1-1-1'],fontSize:20};delete raw.settlement;
  const before=JSON.stringify(raw),m=clone(raw);assert.equal(m.version,8);assert(m.ti.eq(57+(version===6&&paid?30:0)));assert(m.pages.eq(raw.pages));assert(m.lifetimeTi.eq(raw.lifetimeTi));assert(m.tiThisNetwork.eq(raw.tiThisNetwork));assert.deepEqual(m.producers,raw.producers);assert.deepEqual(m.purchaseQueue,raw.purchaseQueue);assert.deepEqual(m.reading,raw.reading);assert.equal(m.specialization,raw.specialization);assert.equal(JSON.stringify(raw),before);
  const twice=S.parseSaveText(S.makeEnvelope(m)).state;assert(twice.ti.eq(m.ti));assert.deepEqual(twice.settlement,m.settlement);assert.deepEqual(twice.purchaseQueue,m.purchaseQueue);
 }
});
test('visual data is bounded and rejects hostile keys and decoration values',()=>{const raw=G.createState();raw.settlement={buildings:{scribe:Infinity,copyist:1e20,__proto__:9},decorations:{banner:'<img onerror=x>',planting:'constructor'},onboarding:{commission:true}};const s=clone(raw);assert.equal(s.settlement.buildings.scribe,0);assert.equal(s.settlement.buildings.copyist,100000);assert.equal(s.settlement.decorations.banner,'indigo');assert.equal(s.settlement.decorations.planting,'olive');assert(!G.setSettlementDecoration(s,'__proto__','x'));assert(!G.setSettlementDecoration(s,'banner','<svg>'));assert(G.setSettlementDecoration(s,'banner','clay'));});
test('first hire creates an operating building and 25 hires develop it',()=>{const s=G.createState();G.tick(s,5);assert.equal(G.buyProducer(s,'scribe',1).bought,1);let m=V.derive(s);assert.equal(m.sites[0].stage,1);assert.equal(m.sites[0].workers,1);s.pages=G.bn('1e10');G.buyProducer(s,'scribe',24);m=V.derive(s);assert.equal(m.sites[0].stage,3);assert.equal(m.sites[0].workers,4);assert.equal(s.settlement.buildings.scribe,25);});
test('each of six sites derives the corresponding authoritative producer and Method',()=>{for(const site of V.sites){const s=G.createState();s.pages=G.bn('1e20');G.buyProducer(s,site.id,1);G.buyPageUpgrade(s,site.method);const m=V.derive(s).sites.find(p=>p.id===site.id);assert(m.operating&&m.equipment);assert.equal(m.owned,s.producers[site.id]);assert(m.contribution.gt(0));}});
test('Organized Desk unlocks approaches; later changes wait until Translation',()=>{const s=G.createState();assert(!G.specializationUnlocked(s));assert(!G.setSpecialization(s,'publisher'));s.pages=G.bn(1000);G.buyPageUpgrade(s,'desk');assert(G.specializationUnlocked(s));assert(G.setSpecialization(s,'publisher'));assert.equal(s.specialization,'publisher');G.setSpecialization(s,'teacher');assert.equal(s.specialization,'publisher');assert.equal(s.queuedSpecialization,'teacher');s.peakPages=G.bn('1e15');assert(G.completeTranslation(s).ok);assert.equal(s.specialization,'teacher');assert.equal(s.queuedSpecialization,null);assert(G.specializationUnlocked(s));});
test('Translation retains architecture, cosmetics, commission history and plans, not workforce',()=>{const s=G.createState();s.pages=G.bn('1e15');s.peakPages=s.pages;G.buyProducer(s,'scribe',25);G.buyPageUpgrade(s,'desk');G.completeProject(s,'manuscript');G.setSettlementDecoration(s,'courtyard','fountain');G.enqueuePurchase(s,{type:'producer',id:'scribe',target:50});const old=V.derive(s);assert(G.completeTranslation(s).ok);const m=V.derive(s);assert.equal(m.sites[0].stage,3);assert.equal(m.sites[0].workers,0);assert(!m.sites[0].operating);assert(!m.sites[0].equipment);assert(m.commissions.manuscript);assert.equal(m.decorations.courtyard,'fountain');assert.equal(s.purchaseQueue.orders.length,1);assert(V.events(old,m).some(e=>e.type==='departure'));});
test('view models and purchase/reset previews never mutate a save',()=>{const s=G.createState();s.pages=G.bn('1e16');s.peakPages=s.pages;const snapshot=JSON.stringify(s);V.derive(s);for(const p of G.PRODUCERS)W.purchase(s,p,'max');W.resetPreview(s,'translation');assert.equal(JSON.stringify(s),snapshot);});
test('editable target validation, completion and return recap agree',()=>{const s=G.createState();s.pageUpgrades.desk=1;G.enqueuePurchase(s,{type:'producer',id:'scribe',target:5});assert(!G.setPurchaseOrderTarget(s,0,Infinity));assert(!G.setPurchaseOrderTarget(s,0,0));assert(G.setPurchaseOrderTarget(s,0,25));s.pages=G.bn('1e8');const r=G.simulateOffline(s,3600);assert.equal(r.ordersCompleted,1);assert(r.milestones.includes('Scribe'));assert.equal(s.producers.scribe,25);assert.equal(s.purchaseQueue.orders.length,0);});
test('one hour, eight hours, one day and seven days retain identical queue economics and visual history',()=>{for(const duration of [3600,28800,86400,604800]){const s=G.createState();s.pageUpgrades.desk=1;G.enqueuePurchase(s,{type:'producer',id:'copyist',target:25});G.enqueuePurchase(s,{type:'method',id:'copying'});G.enqueuePurchase(s,{type:'producer',id:'editor',target:10});G.setSpecialization(s,'publisher');const a=clone(s),b=clone(s);for(let t=0;t<duration;t++)G.tick(a,1);G.simulateOffline(b,duration);assert.deepEqual(a.producers,b.producers);assert.deepEqual(a.purchaseQueue,b.purchaseQueue);assert.deepEqual(a.settlement,b.settlement);assert(Math.abs(a.pages.log10-b.pages.log10)<1e-8);}});
test('art fallbacks, bounded effects and hidden-tab pause are included in the actual release',()=>{const scene=fs.readFileSync('settlement-scene.js','utf8'),html=fs.readFileSync('index.html','utf8');assert(scene.includes("document.hidden||document.body.dataset.surface!=='settlement'"));assert(scene.includes('effects.slice(-12)'));assert(scene.includes("loader.load(key,'low'"));assert(!html.includes('href="interface.css"'));assert(!html.includes('href="styles.css"'));assert(html.includes('id="buildingList"'));assert(html.includes('id="selectionTray"'));});
fs.mkdirSync('docs/qa-v2.7',{recursive:true});fs.writeFileSync('docs/qa-v2.7/settlement-results.json',JSON.stringify({checks,passed:checks,failed:0},null,2));console.log('Settlement: '+checks+' checks passed.');

