'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),crypto=require('crypto'),G=require('../game-core'),S=require('../save-format'),D=require('../presentation-disclosure'),V=require('../settlement-model'),A=require('../appearance-model'),F=require('../full-backup'),R=require('../settlement-animation'),C=require('../settlement-clips');let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('economy, numeric engine and save envelope are byte-identical to v2.9',()=>{for(const f of ['game-core.js','bignum.js','save-format.js'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),crypto.createHash('sha256').update(fs.readFileSync('tests/baseline-v2.9/'+f)).digest('hex'));});
test('Reference is optional and current-run ownership gates only detailed disclosure',()=>{const s=G.createState();assert.equal(D.reference(s),null);s.pages=G.bn('1e10');const pps=G.pageProduction(s);assert(G.buyPageUpgrade(s,'reference'));assert(G.pageProduction(s).eq(pps));assert(s.pages.eq('9e9'));assert(D.reference(s));s.peakPages=G.bn('1e12');G.completeTranslation(s);assert.equal(D.reference(s),null);assert.equal(G.PAGE_UPGRADES.find(x=>x.id==='reference').cost,'1e9');});
test('Reference relationships reconcile to authoritative totals for every approach and Field',()=>{for(const approach of [null,'scholar','publisher','teacher'])for(const field of [null,...G.FIELDS.map(x=>x.id)]){const s=G.createState();s.specialization=approach;s.runTime=2500;s.pageUpgrades.reference=1;s.projects={manuscript:true,reference:true,teaching:true};s.tiUpgrades.training=3;for(const id of Object.keys(s.producers))s.producers[id]=37;if(field){s.field.active=true;s.field.activeId=field;}const snapshot=JSON.stringify(s),r=D.reference(s),sum=r.relationships.reduce((n,p)=>n.add(p.contribution),r.base);assert(sum.div(r.total).gte(.99999999999)&&sum.div(r.total).lte(1.00000000001));assert.equal(JSON.stringify(s),snapshot);}});
test('Reference Project explains synergy even without higher producers; milestone copy is producer-specific',()=>{const s=G.createState();assert(D.commission(s,'reference').ratio.eq(1));assert.match(D.commission(s,'reference').effect,/0.05/);assert(!D.milestone(s,'scribe').includes('self'));s.producers.scriptorium=50;assert.match(D.milestone(s,'scriptorium'),/no higher/);});
test('all 36 authored locations, defaults and curated arrangements validate',()=>{for(const d of A.definitions){assert.equal(A.choices(d.id).length,3);for(const p of A.choices(d.id))assert(A.validate({[d.id]:p.id}).ok,d.id+'/'+p.id);}assert(A.validate(A.fromLegacy(A.definitions.map(d=>d.id))).ok);for(const p of Object.values(A.presets))assert(A.validate(p.placements).ok);assert(!A.validate({pergola:'anywhere'}).ok);assert(!A.validate({pergola:'eastGarden',market:'eastGarden'}).ok);assert(!A.validate(JSON.parse('{"__proto__":"home"}')).ok);});
test('full backups preserve the exact envelope, validate completely and omit device settings',()=>{const raw=S.makeEnvelope(G.createState(),1234),text=F.make(raw,A.presets.studyCourtyard.placements),parsed=F.parse(text);assert.equal(parsed.economic,raw);assert.deepEqual(parsed.placements,A.presets.studyCourtyard.placements);assert(!text.includes('quality'));assert.equal(F.parse(raw).full,false);const bad=JSON.parse(text);bad.appearance.placements.pergola='arbitrary';assert.throws(()=>F.parse(JSON.stringify(bad)),/checksum/);bad.checksum=S.hashString(JSON.stringify({kind:bad.kind,version:1,economic:bad.economic,appearance:bad.appearance}));assert.throws(()=>F.parse(JSON.stringify(bad)),/Unknown/);});
test('full import commits both values, keeps recovery, and rolls back each interrupted write',()=>{const original=S.makeEnvelope(G.createState()),later=G.createState();later.pages=G.bn(12345);const parsed=F.parse(F.make(S.makeEnvelope(later),A.presets.marketLane.placements)),keys={save:'save',backup:'backup',preferences:'prefs'},prefs={quality:'low',motion:'reduce',placements:{fountain:'home'}};for(let fail=0;fail<=6;fail++){const data=new Map([['save',original],['prefs',JSON.stringify(prefs)]]);let writes=0;const storage={getItem:k=>data.get(k)??null,setItem(k,v){writes++;if(writes===fail)throw Error('interrupted');data.set(k,v);},removeItem:k=>data.delete(k)};if(fail>0&&fail<=5){assert.throws(()=>F.commit(storage,parsed,original,prefs,keys));assert.equal(F.parse(data.get('save')).state.pages.format(),G.createState().pages.format());assert.deepEqual(JSON.parse(data.get('prefs')).placements,prefs.placements);}else {F.commit(storage,parsed,original,prefs,keys);assert.equal(JSON.parse(data.get('prefs')).quality,'low');assert.deepEqual(JSON.parse(data.get('prefs')).placements,parsed.placements);assert(F.parse(data.get(F.RECOVERY_KEY)).full);}}});
test('historical visual stages remain while current-run activity and equipment disappear',()=>{const s=S.parseSaveText(fs.readFileSync('tests/fixtures/settlement/developed.json','utf8')).state,before=V.derive(s);G.completeTranslation(s);const after=V.derive(s);assert(after.sites.every((p,i)=>p.stage===before.sites[i].stage));assert(after.sites.every(p=>p.workers===0&&!p.equipment&&!p.operating));assert.deepEqual(after.commissions,before.commissions);});
test('independent clips cover six routines and all workers travel without entering buildings',()=>{const roles=new Set();for(const s of V.sites)for(let i=0;i<4;i++){roles.add(C.role(s.id,i));for(let t=0;t<120000;t+=250){const p=R.worker(s,i,t,false);for(const b of V.sites)assert(!(p.x>b.x-b.w*.26&&p.x<b.x+b.w*.26&&p.y>b.y-b.h*.39&&p.y<b.y-9));}assert.deepEqual(R.worker(s,i,0,true),R.worker(s,i,100000,true));}for(const role of ['write','check','stack','teach','press'])assert(roles.has(role));});
test('post-reset objectives select useful Methods and eligible major actions without distant reset bars',()=>{const s=G.createState();s.translations=1;s.producers.scribe=10;assert.equal(V.chapter(s).detail,'methods');s.peakPages=G.bn('1e12');assert.equal(V.chapter(s).screen,'translation');s.tiThisNetwork=G.bn(1200);assert.equal(V.chapter(s).screen,'network');});
fs.mkdirSync('docs/qa-v2.10',{recursive:true});fs.writeFileSync('docs/qa-v2.10/presentation-results.json',JSON.stringify({passed,failed:0},null,2));console.log('v2.10 presentation: '+passed+' groups passed');
