"""Rebuild offline readings from the publisher's HTML archive, without rewriting verses.
Usage: python tools/build-scripture.py path/to/engwebp_html.zip
Only whitespace and HTML presentation/footnote markers are normalized.
"""
from pathlib import Path
import sys, re, json, zipfile, hashlib, html
root=Path(__file__).resolve().parents[1]
archive=Path(sys.argv[1]); z=zipfile.ZipFile(archive)
names='Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|1 Samuel|2 Samuel|1 Kings|2 Kings|1 Chronicles|2 Chronicles|Ezra|Nehemiah|Esther|Job|Psalm|Proverbs|Ecclesiastes|Song of Solomon|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|1 Corinthians|2 Corinthians|Galatians|Ephesians|Philippians|Colossians|1 Thessalonians|2 Thessalonians|1 Timothy|2 Timothy|Titus|Philemon|Hebrews|James|1 Peter|2 Peter|1 John|2 John|3 John|Jude|Revelation'.split('|')
codes='GEN EXO LEV NUM DEU JOS JDG RUT 1SA 2SA 1KI 2KI 1CH 2CH EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZK DAN HOS JOL AMO OBA JON MIC NAM HAB ZEP HAG ZEC MAL MAT MRK LUK JHN ACT ROM 1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT PHM HEB JAS 1PE 2PE 1JN 2JN 3JN JUD REV'.split()
books=dict(zip(names,codes)); books['Psalms']='PSA'
pattern=r'('+'|'.join(sorted(books,key=len,reverse=True))+r') (\d+):(\d+)(?:[–-](\d+))?'
source='\n'.join((root/f).read_text(encoding='utf-8') for f in ['content.js','content-depth.js','early-game.js','midgame-depth.js','field-depth.js','legacy-depth.js','index.html'])
refs=sorted(set(re.findall(pattern,source)))
chapters={}; entries=[]; hashes={}
for book,ch,start,end in refs:
 code=books[book]; fn=f'{code}{int(ch):03d}.htm' if code=='PSA' else f'{code}{int(ch):02d}.htm'
 key=f'{code}-{ch}'
 if key not in chapters:
  raw=z.read(fn); hashes[fn]=hashlib.sha256(raw).hexdigest()
  text=raw.decode('utf-8-sig').split('<ul class=\'tnav\'>')[1:]
  text=raw.decode('utf-8-sig'); text=text[text.index('class="main"'):]
  text=re.split(r'<ul class=[\'\"]tnav',text)[0]
  original_parts=re.split(r'<span class="verse" id="V(\d+)">.*?</span>',text,flags=re.S)
  notes={}
  for j in range(1,len(original_parts),2):
   found=re.findall(r'<span class="popup">(.*?)</span>',original_parts[j+1],flags=re.S)
   if found: notes[int(original_parts[j])]=[' '.join(html.unescape(re.sub('<[^>]+>',' ',x)).split()) for x in found]
  text=re.sub(r'<a\b[^>]*class="notemark"[^>]*>.*?</a>','',text,flags=re.S)
  text=re.sub(r'<div class=[\'\"](?:s\d*|r|d|mt\d*)[\'\"][^>]*>.*?</div>','',text,flags=re.S)
  parts=re.split(r'<span class="verse" id="V(\d+)">.*?</span>',text,flags=re.S)
  verses=[]
  for i in range(1,len(parts),2):
   plain=html.unescape(re.sub('<[^>]+>',' ',parts[i+1]))
   plain=' '.join(plain.split())
   verses.append({'number':int(parts[i]),'text':plain,'notes':notes.get(int(parts[i]),[])})
  assert verses,fn
  assert all(v['text'] or v['notes'] for v in verses),fn
  chapters[key]={'book':book,'chapter':int(ch),'verses':verses,'source':'https://ebible.org/engwebp/'+fn}
 first=int(start); last=int(end or start)
 assert all(any(v['number']==n for v in chapters[key]['verses']) for n in range(first,last+1)),(book,ch,start,end)
 entries.append({'id':f'{code.lower()}-{ch}-{start}-{end or start}','reference':f'{book} {ch}:{start}'+('–'+end if end else ''),'chapterKey':key,'start':first,'end':last})
data={'edition':'World English Bible (engwebp)','source':'https://ebible.org/engwebp/','license':'Public domain','retrieved':'2026-09-23','entries':entries,'chapters':chapters}
(root/'scripture-data.js').write_text('/* Publisher text; generated by tools/build-scripture.py. */\n(function(r){const data='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+'; if(typeof module!=="undefined"&&module.exports)module.exports=data; r.WTTNScripture=data;})(globalThis);\n',encoding='utf-8')
(root/'docs'/'scripture-provenance.json').write_text(json.dumps({'source':'https://ebible.org/Scriptures/engwebp_html.zip','archiveSha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'chapterSha256':hashes,'passages':len(entries),'normalization':'HTML and footnote markers removed; whitespace normalized; verse wording unchanged.'},indent=2),encoding='utf-8')
print(f'{len(entries)} passages; {len(chapters)} context chapters')
